system:
  host: "127.0.0.1"
  port: 8089
  env: "debug"
zap:
  format: "console"
  mode: "dev"
  warn_filename: "./douyin-warn.log"
  info_filename: "./douyin-info.log"
  max_size: 10
  max_age: 30
  max_backups: 5
  local_time: 1
redis:
  host: "127.0.0.1"
  port: 6379
  # password: "123456"
  password: ""
  pool_size: 100
  db: 6
mysql:
  host: "127.0.0.1"
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  user: "root"
  password: "123456"
  db_name: "douyin"
  log_level: "error"
  max_idle_conns: 10
  max_open_conns: 100
jwt:
  secret: "douyin"
  expires: 168
  issuer: "root"
upload:
  video_local_path: "upload/videos"
  cover_local_path: "upload/covers"
  url_path: "http://172.16.32.22:8089/"
